//HEADER ACTIONS
export const CHECK_INPUT_HEADER = "CHECK_INPUT_HEADER";
export const CHECK_FILMS_HEADER = "CHECK_FILMS_HEADER";
export const INPUT_VALUE_HEADER = "INPUT_VALUE_HEADER";

//SECTION FILMS ACTIONS
export const CHECKED_FILMS = "CHECKED_FILMS";
export const GET_FILMS_ERROR = "GET_FILMS_ERROR";
export const GET_FILMS_LOADING = "GET_FILMS_LOADING";
export const GET_FILMS_SUCCSES = "GET_FILMS_SUCCSES";

//MODAL ACTIONS
export const ID_FILM = "ID_FILM";
export const CHECKED_MODAL = "CHECKED_MODAL";
export const GET_FILMS_MODAL_ERROR = "GET_FILMS_MODAL_ERROR";
export const GET_FILMS_MODAL_SUCCSES = "GET_FILMS_MODAL_SUCCSES";
export const GET_FILMS_MODAL_LOADING = "GET_FILMS_MODAL_LOADING";

//GLOBAL SEARCH FILTER ACTIONS
export const ADD_FILTER_TEXT_GLOBAL = "ADD_FILTER_TEXT_GLOBAL";
export const CHECK_MENU_GLOBAL = "CHECK_MENU_GLOBAL";
export const CHECK_FILMS_GLOBAL = "CHECK_FILMS_GLOBAL";
export const GET_FILMS_GLOBAL_ERROR = "GET_FILMS_GLOBAL_ERROR";
export const GET_FILMS_GLOBAL_LOADING = "GET_FILMS_GLOBAL_LOADING";
export const GET_FILMS_GLOBAL_SUCCSES = "GET_FILMS_GLOBAL_SUCCSES";
